[package]
name = "smtpc"
version = "0.1.0"
authors = ["teawithsand <teawithsand@gmail.com>"]
edition = "2018"
repository = "https://github.com/teawithsand/smtpc"

[dependencies]
derive_more = "0.15.0"
serde = "1.0"
serde_derive = "1.0"
base64 = "0.10"
mime = "0.3"